### ISSUE TITLE
Error converting .jpg to .webp

### ISSUE THREAD

**Issue by linbaird** [axelrindle/vscode-webp#7]
## Problem Description

Getting Error in VScode

> Failed to convert filename.jpg into a WebP file!

## Logs

*Include any logs from the developer console here*
![Screenshot 2024-05-07 at 11 15 35 am](https://github.com/axelrindle/vscode-webp/assets/30517556/fd96702c-7e94-4122-b70d-38dd98efc41e)

## System Information

Operating System:  OSX 13.2.1
CPU Type: x64/x86
Extension Version: v0.4.1
VSCode Version: 1.88.1

**Comment by axelrindle** [comment]
Thanks you for reporting this, but without any further information I won't be able to reproduce the issue.

Please fill out the form I added to your comment.
